services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/data:/app/data
    environment:
      - ADMIN_SESSION=ECHIDNA_ADMIN


  admin-bot:
    build: ./admin-bot
    depends_on:
      - web
    environment:
      - WEB_HOST=http://web:8000
      - ADMIN_SESSION=ECHIDNA_ADMIN